//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera_Piloto
    {
        public long idPiloto { get; set; }
        public long idCarrera { get; set; }
    }
}
