//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_Piloto
    {
        public int dniPiloto { get; set; }
        public long idCategoria { get; set; }
        public string auto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Piloto Piloto { get; set; }
    }
}
