//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceControl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesRaceControl : DbContext
    {
        public EntidadesRaceControl()
            : base("name=EntidadesRaceControl")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Torneo> Torneo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Categoria_Piloto> Categoria_Piloto { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Carrera_Piloto> Carrera_Piloto { get; set; }
        public virtual DbSet<Piloto> Piloto { get; set; }
    }
}
