//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neumatico
    {
        public int numNeumatico { get; set; }
        public System.DateTime fecha { get; set; }
        public bool nuevo { get; set; }
        public long idUsuario { get; set; }
        public long idTecnica { get; set; }
    
        public virtual Tecnica Tecnica { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
