//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observacion
    {
        public long idObservacion { get; set; }
        public Nullable<long> idRevision { get; set; }
        public Nullable<long> idRevisionOk { get; set; }
        public bool ok { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechaOk { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idUsuarioOk { get; set; }
    
        public virtual Revision Revision { get; set; }
        public virtual Revision Revision1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
